name: quickcheck-arbitrary-template
version: 0.2.0.0
synopsis: Generate QuickCheck Gen for Sum Types
description: Building Sum Type arbitrary instance is kind of a pain. This tool helps automate the process.
homepage: https://github.com/plow-technologies/quickcheck-arbitrary-adt#readme
category: Testing
author: Scott Murphy <scottmurphy09@gmail.com>
maintainer: Scott Murphy <scottmurphy09@gmail.com>
license: BSD3
github: plow-technologies/quickcheck-arbitrary-template
copyright: 2016-2018 Plow Technologies
extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4 && < 5
- QuickCheck  
- safe
- template-haskell >= 2.11 && < 2.13
ghc-options:
- -Wall
#- -Werror

library:
  source-dirs: src
  exposed-modules:
  - Test.QuickCheck.TH.Generators
  - Test.QuickCheck.TH.Generators.Internal
  - Test.QuickCheck.TH.Generators.Internal.BuildArbitrary

tests:
  spec:
    main: Spec.hs
    source-dirs:
    - src
    - test
    dependencies:    
    - tasty
    - tasty-golden
    - tasty-hunit
    - tasty-quickcheck      
